(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 24,
	color: "#663300",
	manifest: [
		{src:"images/CASE.png", id:"CASE"},
		{src:"images/wood.jpg", id:"wood"}
	]
};



// symbols:



(lib.CASE = function() {
	this.initialize(img.CASE);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,211);


(lib.wood = function() {
	this.initialize(img.wood);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,800,200);


(lib.Символ20 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFCC").s().p("Eg4xAI5IAAxxMBxjAAAIAARxg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-363.4,-57,727,114);


(lib.Символ15 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AixBTQgPgDgKgKQgKgJgFgRQgDgJgCgLIgBgYQAAgNABgLQACgLADgJQAGgRALgJQALgJAQgDQAPgDATAAQASAAAPADQAQADALAFIgJAbIgjgJIgQgBQgKAAgJABQgKACgGAFQgGAGgFAMQgDALAAAUQAAARACAMQADAMAGAGQAGAHAKACQAJACAPAAIAQgBIAOgEIAAgqIgmAAIACgaIBFAAIAABXIgNAFIgkAIIgTABQgTAAgQgDgACHBTIAAiJIgzAAIADgcICJAAIgCAcIg0AAIAACJgAgrBTIAAilIB7AAIgCAcIhWAAIAAAnIBDAAIAAAaIhDAAIAAAsIBYAAIgCAcg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-22.4,-8.6,44.9,17.3);


(lib.Символ13 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(1,1,1).p("AAAhuIAADd");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,-12.1,2,24.4);


(lib.Символ11 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AzzqiMAjiAAAIEFU2MgnnAAPg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-126.8,-67.5,253.7,135.1);


(lib.Символ10 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Av+N9Ig+jdIhfiyQhbioAAgdQAAgnAagxQAYgyAAgIQAAh+gviHQgbhLgGgZQgPg5AAg3QAAhRAkg/QAfg1AxgcQAbgPAYgDIgDgNQgHgogBgnQAAhBCPg4QBUgfAsgSQBNgeAugeQBshGCUg0QDRhKAABnQAAAelJCgQk9CbgSAAQgQAAgQgNQgQgNgDAAQgJAAgGAEQgGAFgMACQACARAAAqQAAAtgCAIQgIAhgfAFQgEALgNALQgLALggAWQg/AxAABQQAAAiAPAtIAiBaQAvCIAACdQAAApgaAsQgaArAAAXQBLCcBLCjQCVFGAAAoQAAAVgKAPQgOAXgcAAQg0AAgziUgApyMzQhijxglhDQgZgrgfhUIgyiIQgphsg/gsQgagRgHgOQgMgWAAgvQAAgJAIg6QAHg5AAgJQAAgKgHhOQgIhPAAgJQAAgYARgnQAQgnATgWQAWgYAOAPQAKAMAEAhIABABQA8AwApBgQASAnAgA8IA9BwQAgA6BKDKQA8CmAPAAQAKAACWgxQCug5BSgqQBGgkBrghQBEgUBygcQAzgMBXhDQBYhBArgLQBFgQB6hAIAegQQAIgTAYABIAtgbQAhAAANAbQAGAOABAPIgBALQAdATAgAcQBRBFA1BWQA8BjAABUQAAAXgMARQgNAUgbAAQggAAgshgQgphrgKgVQgXgyhjhGIgWgQIgFACQhEAoiRAoQg/ARhjBBQhnBDhLAYImOCaQlDB7hUAAQgvAAhMioQhAiOgbh0QgRhNhiiuIgQgeIAFBCIgIBKIgHBBQAAADAUAGQAbAIAUAQQBHA3ATCeQAGA4AnBFQAWAoAvBMQA2BfBXC3QBXC4AAATQAAASgJAQQgOAWgcAAQhDAAhfjPgAStBNQg0iJgQglQgjhrgWgyQgmhXhFgeQjAhWhijOQgOgfgIgsIgMhMQgFgWgtg/Qgsg8AAgDQAAhLBBAiQAyAaAeAoQAeAcAQAzQAFARANA9QAkC5DRBzQB7BDAhBJQAKAVAMAvQAMAxAOAfQAVAxAmBjQA0CFAAAXQAAAmgDANQgLAignAAQgTAAgvh4g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-131.6,-104.1,263.3,208.3);


(lib.Символ9 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(0,255,0,0)","#FFFFFF","rgba(0,255,0,0)"],[0,0.537,1],-31.1,-18.2,31.1,18.1).s().p("AqUGjIK6ywIJvFrIq6Swg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-66.1,-78.2,132.3,156.5);


(lib.Символ6 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.CASE();
	this.instance.setTransform(-146.1,-31.4,0.815,0.815,-23);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-146.1,-126.9,292.4,253.9);


(lib.Символ4 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#33CC00").s().p("AC/EFQgHgEgEgHQgDgHgBgHIARAAIAEAHQACAFAFACQAHAGAMAAQAQAAAJgJQAJgJAAgPIAAgRQgGAJgJAFQgLAFgJAAQgWAAgOgPQgHgIgDgJQgDgGAAgIIATAAQABAMAIAIQAJAKAOAAQAOAAAKgLQAIgIABgLIASAAIAAArIABAAQAAAVgPAPQgNAOgZAAQgTAAgNgLgAFdDkQgWAAgQgPQgMgNgBgVIBmAAIAAABIhUAAQAAAHACAGQADAFAFAFQAIAJAQAAQATAAAMgQIAPAIQgIAMgMAGQgLAGgPAAgAAeDgQgJgEgJgIQgHgIgEgIQgBgIgBgJIASAAQAAANAKAJQAEAFAGADQAGADAHAAQAIAAAHgDQAFgDAFgFQAFgFADgHIACgKIATAAQgBAJgEAIQgDAIgIAIQgIAIgKAEQgJAEgLAAQgLAAgJgEgAmVDVQgHgIgEgJQgCgIgBgJIATAAQAAAGACAEQACAHAFAFQAKAKAQAAIAAABQAGAAAGgDQAGgDAFgFQAJgKACgMIASAAIAAAuIgSAAIAAgPQgHAIgKAFQgKAFgKAAQgXAAgOgPgAICDgQgEgEAAgFQAAgFADgEQAEgEAFAAIAAAAQAGAAADAEQAEAEAAAFQAAAFgEAEQgDADgGAAQgFAAgDgDgAGsDhIAAguIARAAIAAAugAgwDhIAAguIASAAIAAAugAilDhIAAguIASAAIAAAugAjZDhIAAguIARAAIAAAugAkdDhIAAguIATAAIAAAugAneDhIgSguIASAAIAGAQIAHgQIAQAAIgSAugAofDhIgTguIATAAIAGARIAHgRIAQAAIgTAugAICC7IAAgCIABgGIASAAIgBAFIAAADgAFVArIAYgzIgRglIAUAAIAIARIAHgRIASAAIgpBYgAh7ArIAZgzIgRglIAUAAIAHARIAIgRIASAAIgpBYgAI8gKQgMgMAAgTIAAgEIATAAIAAAEQAAAGACAEQABAFAEADQAHAIALAAQAKAAAHgIQAEgDABgFQACgEAAgGIAAgEIARAAIAAAEQAAAKgCAIQgDAHgFAGQgMAKgTAAQgUAAgMgKgAHTgDQgJgEgIgHQgHgJgEgIQgDgHgBgHIATAAQACALAIAIQAEAFAHADQAGADAHAAQAHAAAHgDQAGgDAFgFQAEgFADgGIABgIIAUAAQgBAHgDAHQgEAIgHAJQgJAHgJAEQgJADgLAAQgLAAgKgDgAC4gDQgJgEgIgHQgIgJgEgIQgCgHgBgHIATAAQACALAHAIQAFAFAGADQAGADAIAAQAHAAAGgDQAGgDAFgFQAFgFADgGIACgIIASAAQgBAHgCAHQgFAIgHAJQgIAHgKAEQgIADgMAAQgLAAgJgDgAjJAAQgWAAgPgOQgMgMgCgTIASAAQAAAGADAFQADAFAEAFQAJAJAPAAQATAAANgQIAPAIQgIAMgNAGQgKAFgQAAgAnFgDQgJgEgIgHQgIgJgEgIQgCgHgBgHIATAAQACALAHAIQAFAFAGADQAGADAIAAQAHAAAHgDQAGgDAEgFQAFgFADgGIABgIIATAAQAAAHgDAHQgEAIgIAJQgIAHgJAEQgJADgMAAQgKAAgKgDgAAmgOQgGgIgEgJQgDgGAAgIIATAAIACAIQACAGAFAFQAJAKAQAAIAAABQAHAAAGgDQAGgDAFgFQAHgIACgLIATAAIAAArIgSAAIAAgPQgGAHgKAGQgLAEgKAAQgWAAgPgOgAkjgCIAAgrIASAAIAAArgAlmgCIAAgrIASAAIAAArgAoMgCIAAgrIATAAIAAAqIAAABgApIgCIAAgrIATAAIAAArgAqEgCIAAgrIASAAIAAArgAE8jgQgJgEgIgHQgOgPgBgVIATAAIACALQADAHAFAFQAJAKAQAAQAHAAAHgCIAPgFIAAARQgHAEgIABQgHACgHAAIAAABQgMAAgKgEgAC+joQgLgMAAgSIAAgJIASAAIAAAJQAAAFACAFQABAFAEADQAGAIALAAQALAAAHgIQADgDACgFQACgFAAgFIAAgJIASAAIAAAJQAAAJgEAIQgCAIgFAFQgMAMgUAAQgTAAgMgMgAkljgQgJgFgJgHQgHgIgEgJQgEgIAAgKIATAAQABAOAJAKQAFAFAGACQAGAEAHAAQAIAAAGgEQAGgCAFgFQAFgGACgGIACgMIAUAAQgBAKgEAIQgEAJgHAIQgIAHgKAFQgJAEgLAAQgLAAgJgEgAHFjgIAAgvIARAAIAAAvgAGBjgIAAgvIATAAIAAAvgACGjgIAAgvIATAAIAAAvIAAAAgABKjgIAAgvIATAAIAAAvgAAOjgIAAgvIASAAIAAAvgAhpjgIgTgvIARAAIAHARIAHgRIARAAIgTAvgAirjgIgTgvIASAAIAHASIAIgSIAQAAIgUAvgAlxjgIAAgvIAUAAIAAAvgAnTjgIAAgvIAUAAIAAAvg");
	this.shape.setTransform(-2.2,7.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#66FF01").s().p("AIDEXQAAgGADgHQAEgHAJgFQARgLAFgHQAFgJAAgJQAAgGgCgGQgCgFgEgEQgFgFgFgBQgGgDgHAAQgGAAgGACQgFACgEAEQgJAIgCAOIgTAAQACgWAPgOQAPgMAUAAQAKAAAKAEQAJADAHAHQAOANAAAVQAAANgJANQgDAGgHAGQgHAGgKAHQgHADgBADIgBAEgAGsEXIAAglIgTAAIAAgQIATAAIAAgiIARAAIAAAiIAUAAIAAAQIgUAAIAAAlgAEqEXIgBgFQAAgKAEgKQAEgIAHgJQAPgPAXAAQALAAAJAEQAJAEAHAHQAHAIADAJQAEAKAAAMIAAADgAFID2QgFADgDAFIgEALIBBAAQgBgGgDgFQgCgFgFgDQgJgIgLAAQgOAAgIAIgAEBEXIAAgFQAAgIgCgFQgCgHgFgFQgKgJgOgBQgHAAgGADQgGACgEAFQgKAKAAAPIABAFIgTAAIgBgGQAAgVAOgPQAHgHAJgDQAJgEALgBQAJAAAKAFQAKAFAFAIIAAgOIATAAIAAA1gABVEXIAAgEQAAgHgCgHQgDgGgFgGQgJgKgQgBQgHAAgGAEQgGACgEAFQgGAGgCAGQgDAHAAAHIABAEIgSAAIAAgEQAAgLACgJQAEgKAHgHQAJgJAJgCQAJgEALgBIAAAAQALABAKAEQAKACAHAJQAQAPAAAWIAAAEgAgwEXIAAglIgSAAIAAgQIASAAIAAgiIASAAIAAAiIATAAIAAAQIgTAAIAAAlgAilEXIAAglIgSAAIAAgQIASAAIAAgiIASAAIAAAiIAUAAIAAAQIgUAAIAAAlgAjZEXIAAgQQAAgNgFgFQgDgDgEgCQgDgBgGgBQgIABgHAEQgHAFgGAIIAAAXIgTAAIAAg1IATAAIAAAMQAHgJAIgCQAIgEAJgBQAQAAAJALQAEAEADAHQACAHAAAIIAAAUgAlLEXIAAgFQAAgHgEgGQgBgHgGgFQgKgLgOAAQgPAAgJALQgGAEgCAIQgCAGAAAHIAAAFIgTAAIAAgEQAAgVAPgQQAOgPAWAAQAKAAAKAEQAKAGAHAJIAAgPIASAAIAAA0gAnREXIAUg1IASAAIgWA1gAnwEXIgJgYIgJAYIgQAAIAVg1IAKAAIAVA1gAoyEXIgWg1IAUAAIAVA1gAJ0A2IAAg3IARAAIAAA3gAIwA2IAAg3IATAAIAAA3gAIJA2IABgHQAAgIgCgHQgDgGgEgGQgKgKgPAAQgHAAgGACQgHADgEAFQgGAGgCAGQgDAHAAAIIABAHIgTAAIgBgHQAAgMAFgJQAEgKAHgGQAIgJAJgBQAKgEALgBIAAAAQALABAJAEQAKABAIAJQAPAOAAAXIAAAHgAF/A2IAZg3IATAAIgaA3gAFcA2Igag3IAUAAIAaA3gADvA2IAAgHQAAgIgCgHQgDgGgFgGQgJgKgPAAQgIAAgGACQgGADgFAFQgFAGgCAGQgDAHAAAIIABAHIgTAAIgBgHQAAgMAEgJQAEgKAIgGQAIgJAJgBQAJgEALgBIABAAQALABAKAEQAJABAHAJQAQAOAAAXIgBAHgABvA2IABgIQAAgIgCgHQgDgFgFgGQgKgKgOAAQgIAAgFACQgHADgEAFQgGAFgCAGQgDAHAAAIIABAIIgTAAIgBgIQAAgWAPgOQAPgOAVgBQAKABALAEQAJADAHAJIAAhEIASAAIAABugAhQA2IAag3IASAAIAAgBIAAABIAAAAIgaA3gAhzA2Igag3IAUAAIAaA3gAj8A2IAAgIQAAgLADgJQAFgJAHgJQAPgNAWAAQAMABAJADQAJACAHAHQAHAIADAKQADAJAAANIAAADIhUAAIAAADgAjeARQgEADgDAGQgDAEgBAHIBBAAQgBgHgDgEQgDgGgEgDQgJgIgMABQgNgBgJAIgAkjA2IAAgTQAAgOgFgFQgCgDgEgCQgEgBgFAAQgIAAgHAEQgHAFgHAJIAAAaIgSAAIAAg3IASAAIAAALQAHgJAJgBQAIgEAJgBQAQAAAJAIQAEAFADAHQACAHAAAIIAAAYgAmPA2IABgHQAAgIgCgHQgDgGgFgGQgJgKgPAAQgIAAgGACQgGADgFAFQgFAGgCAGQgDAHAAAIIABAHIgTAAIgBgHQAAgMAEgJQAEgKAIgGQAIgJAJgBQAKgEAKgBIABAAQALABAJAEQAKABAHAJQAQAOAAAXIgBAHgAoMA2IAAgTQAAgOgDgGQgFgFgIAAQgHAAgGAEQgGAEgGAKIAAAaIgTAAIAAgTQAAgOgDgFQgCgDgDgCQgEgBgEAAQgIAAgFAEQgHAEgGAKIAAAaIgSAAIAAg4IASAAIAAAKQANgNAQAAQALAAAHAFQAGACADAJQAIgJAIgCQAIgFAKAAQAIAAAFACQAGADAEADQAIAJAAARIAAAZgAGrgBIABgBIAAABgAGrgBgAHFiqIAAgPQAAgNgFgGQgDgDgEgCIgJgBQgHABgIAEQgHAEgGAJIAAAWIgTAAIAAhsIATAAIAABDQAIgHAHgEQAJgFAJAAQAPAAAKALQAEAFACAHQACAGAAAIIAAAUgAEciqIAAgDQAAgMAFgJQADgKAHgHQAQgQAXAAQAHAAAIADIAOAEIAAASQgNgIgQAAQgPABgKAJQgKALAAAPIAAAEgAD2iqIAAg0IASAAIAAA0gACziqIAAg0IASAAIAAA0gACGiqIAAgPQAAgOgDgFQgEgGgJAAQgHAAgGAFQgGAEgGAJIAAAWIgTAAIAAgPQAAgNgDgGQgCgDgDgCIgIgBQgIAAgFAFQgHAEgGAJIAAAWIgSAAIAAg1IASAAIAAAMQANgQAQAAQALAAAHAFQAGAFAEAIQAHgIAIgFQAIgFAKAAQAIAAAFADQAGADAEAEQAIAKAAARIAAAUgAhdiqIAVg0IASAAIgWA0gAh8iqIgIgXIgJAXIgQAAIAUg0IAKAAIAUA0gAi+iqIgWg0IAUAAIAUA0gAjviqIAAgDQAAgHgCgHQgCgGgFgGQgKgKgPgBQgHABgGACQgGACgFAGQgFAGgCAGQgDAHAAAHIAAADIgTAAIAAgDQAAgLAEgKQAEgJAHgIQAJgHAJgEQAJgFALAAIAAAAQALAAAKAFQAJAEAIAHQAQAPAAAXIAAADgAlxiqIAAgYIhOAAIAAAYIgUAAIAAhoIAUAAIAAA/IBOAAIAAg/IAUAAIAABog");
	this.shape_1.setTransform(-2.2,-2.1);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-66.8,-30,129.2,65.2);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ20();
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ15();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.621},4).to({alpha:1},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.4,-8.6,44.9,17.3);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ13();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({alpha:0.172},0).wait(5).to({alpha:1},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.5,-11.6,1,23.4);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AC/E7QgHgEgEgIIAAAAQgDgGgBgHIAAAAIARAAIAEAHIAAAAQACAEAFADIAAAAQAHAFAMABIAAAAQAQgBAJgIIAAAAQAJgJAAgQIAAAAIAAgQQgGAJgJAFIAAAAQgLAFgJAAIAAAAQgWAAgOgPIAAAAQgHgIgDgJIAAAAQgDgHAAgIIAAAAIATAAQABAMAIAJIAAAAQAJAJAOABIAAAAQAOAAAKgLIAAAAQAIgIABgMIAAAAIASAAIAAAsIABAAQAAAVgPAPIAAAAQgNAOgZAAIAAAAQgTAAgNgLgAFdEaQgWAAgQgPIAAAAQgMgNgBgWIAAAAIBmAAIAAACIhUAAQAAAHACAGIAAAAQADAFAFAEIAAAAQAIAKAQgBIAAAAQATABAMgRIAAAAIAPAJQgIAMgMAGIAAAAQgLAFgPABIAAAAgAAeEWQgJgEgJgIIAAAAQgHgIgEgJIAAAAQgBgHgBgKIAAAAIASAAQAAANAKAKIAAAAQAEAFAGADIAAAAQAGADAHgBIAAAAQAIABAHgDIAAAAQAFgDAFgFIAAAAQAFgFADgHIAAAAIACgLIAAAAIATAAQgBAKgEAHIAAAAQgDAJgIAIIAAAAQgIAIgKAEIAAAAQgJADgLABIAAAAQgLgBgJgDgAmVELQgHgJgEgJIAAAAQgCgHgBgKIAAAAIATAAQAAAHACAEIAAAAQACAHAFAFIAAAAQAKAKAQAAIAAAAIAAAAQAGABAGgDIAAAAQAGgDAFgFIAAAAQAJgKACgNIAAAAIASAAIAAAvIgSAAIAAgPQgHAHgKAGIAAAAQgKAEgKABIAAAAQgXAAgOgPgAICEWQgEgEAAgFIAAAAQAAgFADgEIAAAAQAEgEAFAAIAAAAIAAAAQAGAAADAEIAAAAQAEAEAAAFIAAAAQAAAFgEAEIAAAAQgDADgGAAIAAAAQgFAAgDgDgAGsEXIAAgvIARAAIAAAvgAgwEXIAAgvIASAAIAAAvgAilEXIAAgvIASAAIAAAvgAjZEXIAAgvIARAAIAAAvgAkdEXIAAgvIATAAIAAAvgAneEXIgSgvIASAAIAGARIAHgRIAQAAIgSAvgAofEXIgTgvIATAAIAGARIAHgRIAQAAIgTAvgAICDwIAAgCIABgGIAAAAIASAAIgBAGIAAAAIAAACgAIDDoQAAgGADgGIAAAAQAEgHAJgGIAAAAQARgKAFgIIAAAAQAFgJAAgJIAAAAQAAgGgCgGIAAAAQgCgFgEgEIAAAAIgKgGIAAAAQgGgDgHAAIAAAAQgGAAgGACIAAAAQgFACgEAEIAAAAQgJAIgCAOIAAAAIgTAAQACgVAPgOIAAAAQAPgNAUAAIAAAAQAKAAAKAEIAAAAQAJADAHAIIAAAAQAOANAAAUIAAAAQAAAOgJANIAAAAQgDAFgHAHIAAAAQgHAGgKAGIAAAAQgHADgBAEIAAAAIgBADIAAAAgAGsDoIAAglIgTAAIAAgPIATAAIAAgjIARAAIAAAjIAUAAIAAAPIgUAAIAAAlgAEqDoIgBgEIAAAAQAAgKAEgKIAAAAQAEgJAHgIIAAAAQAPgPAXAAIAAAAQALAAAJAEIAAAAQAJADAHAIIAAAAQAHAHADAKIAAAAQAEAJAAAMIAAAAIAAADgAFIDHQgFAEgDAFIAAAAIgEALIAAAAIBBAAQgBgGgDgFIAAAAQgCgFgFgEIAAAAQgJgHgLAAIAAAAQgOAAgIAHgAEBDoIAAgEIAAAAQAAgIgCgGIAAAAQgCgHgFgEIAAAAQgKgKgOAAIAAAAQgHAAgGACIAAAAQgGADgEAEIAAAAQgKALAAAPIAAAAIABAEIAAAAIgTAAIgBgFIAAAAQAAgVAOgPIAAAAQAHgIAJgDIAAAAQAJgEALAAIAAAAQAJAAAKAFIAAAAQAKAEAFAJIAAAAIAAgOIATAAIAAA0gABVDoIAAgDIAAAAQAAgIgCgHIAAAAQgDgFgFgGIAAAAQgJgLgQAAIAAAAQgHAAgGADIAAAAQgGACgEAGIAAAAQgGAGgCAFIAAAAQgDAHAAAIIAAAAIABADIAAAAIgSAAIAAgDIAAAAQAAgMACgIIAAAAQAEgKAHgHIAAAAQAJgJAJgDIAAAAQAJgEALAAIAAAAIAAAAQALAAAKAEIAAAAQAKADAHAJIAAAAQAQAPAAAWIAAAAIAAADIAAAAgAgwDoIAAglIgSAAIAAgPIASAAIAAgjIASAAIAAAjIATAAIAAAPIgTAAIAAAlgAilDoIAAglIgSAAIAAgPIASAAIAAgjIASAAIAAAjIAUAAIAAAPIgUAAIAAAlgAjZDoIAAgPQAAgNgFgGIAAAAQgDgDgEgCIAAAAQgDgBgGAAIAAAAQgIAAgHAEIAAAAQgHAFgGAJIAAAAIAAAWIgTAAIAAg0IATAAIAAAMQAHgJAIgDIAAAAQAIgEAJAAIAAAAQAQAAAJAKIAAAAQAEAFADAHIAAAAQACAHAAAHIAAAAIAAAUgAlLDoIAAgEIAAAAQAAgIgEgGIAAAAQgBgHgGgFIAAAAQgKgKgOAAIAAAAQgPAAgJAKIAAAAQgGAFgCAHIAAAAQgCAGAAAIIAAAAIAAAEIAAAAIgTAAIAAgDIAAAAQAAgWAPgPIAAAAQAOgPAWgBIAAAAQAKABAKAEIAAAAQAKAGAHAIIAAAAIAAgPIASAAIAAA0gAnRDoIAUg0IASAAIgWA0gAnwDoIgJgXIgJAXIgQAAIAVg0IAKAAIAVA0gAoyDoIgWg0IAUAAIAVA0gAFVBgIAYg0IgRglIAUAAIAIARIAHgRIASAAIgpBZgAh7BgIAZg0IgRglIAUAAIAHARIAIgRIASAAIgpBZgAI8ApQgMgLAAgTIAAAAIAAgEIATAAIAAAEQAAAFACAFIAAAAQABAFAEADIAAAAQAHAIALAAIAAAAQAKAAAHgIIAAAAQAEgDABgFIAAAAQACgFAAgFIAAAAIAAgEIARAAIAAAEQAAAKgCAIIAAAAQgDAHgFAFIAAAAQgMAMgTAAIAAAAQgUAAgMgMgAHTAxQgJgEgIgHIAAAAQgHgJgEgIIAAAAQgDgHgBgHIAAAAIATAAQACALAIAIIAAAAQAEAFAHADIAAAAQAGADAHAAIAAAAQAHAAAHgDIAAAAQAGgDAFgFIAAAAQAEgFADgHIAAAAIABgHIAAAAIAUAAQgBAHgDAHIAAAAQgEAIgHAJIAAAAQgJAHgJAEIAAAAQgJAEgLAAIAAAAQgLAAgKgEgAC4AxQgJgEgIgHIAAAAQgIgJgEgIIAAAAQgCgHgBgHIAAAAIATAAQACALAHAIIAAAAQAFAFAGADIAAAAQAGADAIAAIAAAAQAHAAAGgDIAAAAQAGgDAFgFIAAAAQAFgFADgHIAAAAIACgHIAAAAIASAAQgBAHgCAHIAAAAQgFAIgHAJIAAAAQgIAHgKAEIAAAAQgIAEgMAAIAAAAQgLAAgJgEgAjJA1QgWAAgPgPIAAAAQgMgMgCgTIAAAAIASAAQAAAGADAFIAAAAQADAFAEAFIAAAAQAJAJAPAAIAAAAQATAAANgQIAAAAIAPAIQgIAMgNAGIAAAAQgKAGgQAAIAAAAgAnFAxQgJgEgIgHIAAAAQgIgJgEgIIAAAAQgCgHgBgHIAAAAIATAAQACALAHAIIAAAAQAFAFAGADIAAAAQAGADAIAAIAAAAQAHAAAHgDIAAAAQAGgDAEgFIAAAAQAFgFADgHIAAAAIABgHIAAAAIATAAQAAAHgDAHIAAAAQgEAIgIAJIAAAAQgIAHgJAEIAAAAQgJAEgMAAIAAAAQgKAAgKgEgAAmAmQgGgIgEgJIAAAAQgDgHAAgHIAAAAIATAAIACAHIAAAAQACAHAFAFIAAAAQAJAKAQAAIAAAAIAAABQAHAAAGgDIAAAAQAGgDAFgFIAAAAQAHgIACgLIAAAAIATAAIAAArIgSAAIAAgQQgGAIgKAGIAAAAQgLAEgKAAIAAAAQgWAAgPgOgAkjAyIAAgrIASAAIAAArgAlmAyIAAgrIASAAIAAArgAoMAyIAAgrIATAAIAAAqIAAABgApIAyIAAgrIATAAIAAArgAqEAyIAAgrIASAAIAAArgAJ0AHIAAg3IARAAIAAA3gAIwAHIAAg3IATAAIAAA3gAIJAHIABgHIAAAAQAAgFgCgHIAAAAQgDgGgEgGIAAAAQgKgKgPAAIAAAAQgHAAgGACIAAAAQgHADgEAFIAAAAQgGAGgCAGIAAAAQgDAHAAAFIAAAAIABAHIAAAAIgTAAIgBgHIAAAAQAAgKAFgJIAAAAQAEgJAHgHIAAAAQAIgJAJgDIAAAAQAKgEALAAIAAAAIAAAAQALAAAJAEIAAAAQAKADAIAJIAAAAQAPAOAAAVIAAAAIAAAHIAAAAgAF/AHIAZg3IATAAIgaA3gAFcAHIgag3IAUAAIAaA3gADvAHIAAgHIAAAAQAAgFgCgHIAAAAQgDgGgFgGIAAAAQgJgKgPAAIAAAAQgIAAgGACIAAAAQgGADgFAFIAAAAQgFAGgCAGIAAAAQgDAHAAAFIAAAAIABAHIAAAAIgTAAIgBgHIAAAAQAAgKAEgJIAAAAQAEgJAIgHIAAAAQAIgJAJgDIAAAAQAJgEALAAIAAAAIABAAQALAAAKAEIAAAAQAJADAHAJIAAAAQAQAOAAAVIAAAAIgBAHIAAAAgABvAHIABgHIAAAAQAAgGgCgHIAAAAQgDgGgFgFIAAAAQgKgKgOAAIAAAAQgIAAgFACIAAAAQgHACgEAGIAAAAQgGAFgCAGIAAAAQgDAGAAAHIAAAAIABAHIAAAAIgTAAIgBgHIAAAAQAAgVAPgOIAAAAQAPgQAVAAIAAAAQAKAAALAFIAAAAQAJAFAHAJIAAAAIAAhGIASAAIAABtgAhQAHIAag3IASAAIAAAAIAAAAIAAAAIgaA3gAhzAHIgag3IAUAAIAaA3gAj8AHIAAgHIAAAAQAAgKADgJIAAAAQAFgJAHgJIAAAAQAPgOAWAAIAAAAQAMAAAJADIAAAAQAJAFAHAGIAAAAQAHAJADAJIAAAAQADAJAAALIAAAAIAAAEIhUAAIAAACIAAAAgAjegcQgEAEgDAFIAAAAQgDAEgBAIIAAAAIBBAAQgBgIgDgEIAAAAQgDgFgEgEIAAAAQgJgHgMAAIAAAAQgNAAgJAHgAkjAHIAAgRQAAgNgFgGIAAAAQgCgDgEgBIAAAAQgEgBgFAAIAAAAQgIAAgHAEIAAAAQgHAEgHAJIAAAAIAAAYIgSAAIAAg3IASAAIAAANQAHgJAJgDIAAAAQAIgEAJAAIAAAAQAQAAAJAKIAAAAQAEAFADAGIAAAAQACAIAAAIIAAAAIAAAVgAmPAHIABgHIAAAAQAAgFgCgHIAAAAQgDgGgFgGIAAAAQgJgKgPAAIAAAAQgIAAgGACIAAAAQgGADgFAFIAAAAQgFAGgCAGIAAAAQgDAHAAAFIAAAAIABAHIAAAAIgTAAIgBgHIAAAAQAAgKAEgJIAAAAQAEgJAIgHIAAAAQAIgJAJgDIAAAAQAKgEAKAAIAAAAIABAAQALAAAJAEIAAAAQAKADAHAJIAAAAQAQAOAAAVIAAAAIgBAHIAAAAgAoMAHIAAgRQAAgOgDgGIAAAAQgFgEgIAAIAAAAQgHAAgGAEIAAAAQgGAEgGAJIAAAAIAAAYIgTAAIAAgRQAAgNgDgGIAAAAQgCgDgDgBIAAAAQgEgBgEAAIAAAAQgIAAgFAEIAAAAQgHAEgGAJIAAAAIAAAYIgSAAIAAg3IASAAIAAALQANgPAQAAIAAAAQALAAAHAFIAAAAQAGAFADAJIAAAAQAIgJAIgFIAAAAQAIgFAKAAIAAAAQAIAAAFADIAAAAQAGADAEAFIAAAAQAIAJAAARIAAAAIAAAWgAGrgwIABAAIAAAAgAGrgwgAE8iqQgJgEgIgIIAAAAQgOgOgBgVIAAAAIATAAIACALIAAAAQADAGAFAGIAAAAQAJAKAQAAIAAAAQAHAAAHgCIAAAAIAPgGIAAAAIAAASQgHADgIACIAAAAQgHACgHAAIAAAAIAAABQgMgBgKgDgAC+iyQgLgMAAgTIAAAAIAAgIIASAAIAAAIQAAAGACAEIAAAAQABAGAEACIAAAAQAGAJALgBIAAAAQALABAHgJIAAAAQADgCACgGIAAAAQACgEAAgGIAAAAIAAgIIASAAIAAAIQAAAKgEAIIAAAAQgCAIgFAFIAAAAQgMAMgUAAIAAAAQgTAAgMgMgAklirQgJgEgJgHIAAAAQgHgIgEgKIAAAAQgEgIAAgJIAAAAIATAAQABAOAJAKIAAAAQAFAEAGADIAAAAQAGADAHAAIAAAAQAIAAAGgDIAAAAQAGgDAFgEIAAAAQAFgHACgFIAAAAIACgMIAAAAIAUAAQgBAJgEAIIAAAAQgEAKgHAIIAAAAQgIAHgKAEIAAAAQgJAFgLAAIAAAAQgLAAgJgFgAHFiqIAAgvIARAAIAAAvgAGBiqIAAgvIATAAIAAAvgACGiqIAAgvIATAAIAAAuIAAABgABKiqIAAgvIATAAIAAAvgAAOiqIAAgvIASAAIAAAvgAhpiqIgTgvIARAAIAHARIAHgRIARAAIgTAvgAiriqIgTgvIASAAIAHARIAIgRIAQAAIgUAvgAlxiqIAAgvIAUAAIAAAvgAnTiqIAAgvIAUAAIAAAvgAHFjZIAAgOQAAgNgFgGIAAAAQgDgEgEgBIAAAAIgJgBIAAAAQgHAAgIAEIAAAAQgHAFgGAJIAAAAIAAAVIgTAAIAAhsIATAAIAABEQAIgIAHgDIAAAAQAJgFAJAAIAAAAQAPAAAKAKIAAAAQAEAGACAGIAAAAQACAHAAAIIAAAAIAAATgAEcjZIAAgCIAAAAQAAgMAFgJIAAAAQADgLAHgGIAAAAQAQgQAXAAIAAAAQAHAAAIACIAAAAIAOAFIAAAAIAAASQgNgIgQAAIAAAAQgPAAgKAKIAAAAQgKAKAAAQIAAAAIAAADIAAAAgAD2jZIAAg0IASAAIAAA0gACzjZIAAg0IASAAIAAA0gACGjZIAAgOQAAgOgDgGIAAAAQgEgFgJAAIAAAAQgHAAgGAEIAAAAQgGAEgGAKIAAAAIAAAVIgTAAIAAgOQAAgNgDgGIAAAAQgCgEgDgBIAAAAIgIgBIAAAAQgIAAgFAEIAAAAQgHAEgGAKIAAAAIAAAVIgSAAIAAg1IASAAIAAANQANgQAQAAIAAAAQALgBAHAGIAAAAQAGAEAEAJIAAAAQAHgJAIgEIAAAAQAIgGAKABIAAAAQAIAAAFACIAAAAQAGAEAEAEIAAAAQAIAJAAARIAAAAIAAAUgAhdjZIAVg0IASAAIgWA0gAh8jZIgIgWIgJAWIgQAAIAUg0IAKAAIAUA0gAi+jZIgWg0IAUAAIAUA0gAjvjZIAAgCIAAAAQAAgIgCgHIAAAAQgCgGgFgFIAAAAQgKgLgPAAIAAAAQgHAAgGACIAAAAQgGADgFAGIAAAAQgFAFgCAGIAAAAQgDAHAAAIIAAAAIAAACIAAAAIgTAAIAAgCIAAAAQAAgMAEgJIAAAAQAEgJAHgIIAAAAQAJgIAJgDIAAAAQAJgFALAAIAAAAIAAAAQALAAAKAFIAAAAQAJADAIAIIAAAAQAQAPAAAXIAAAAIAAACIAAAAgAlxjZIAAgXIhOAAIAAAXIgUAAIAAhnIAUAAIAAA/IBOAAIAAg/IAUAAIAABng");
	mask.setTransform(-2.2,1.8);

	// Слой 2
	this.instance = new lib.Символ9();
	this.instance.setTransform(-127.2,-12.9);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:150.8,y:11.8},39).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.7,-30.7,5.7,65.2);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ6();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:1.3},12,cjs.Ease.get(-1)).to({rotation:3.5},17,cjs.Ease.get(1)).to({rotation:1.8},17,cjs.Ease.get(-1)).to({rotation:0},19,cjs.Ease.get(1)).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ10();
	this.instance_1.setTransform(10.1,18.9);
	this.instance_1.alpha = 0.391;
	this.instance_1.filters = [new cjs.BlurFilter(12, 12, 1)];
	this.instance_1.cache(-134,-106,267,212);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(66));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-146.1,-126.9,296.6,259.7);


(lib.Символ5 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ8();
	this.instance.setTransform(0,0.4);

	// Слой 1
	this.instance_1 = new lib.Символ4();
	this.instance_1.setTransform(0,-0.3);

	this.instance_2 = new lib.Символ4();
	this.instance_2.setTransform(0,1.6);
	this.instance_2.filters = [new cjs.ColorFilter(0.48, 0.48, 0.48, 1, 0, 0, 0, 0)];
	this.instance_2.cache(-69,-32,133,69);

	// Слой 3
	this.instance_3 = new lib.Символ11();
	this.instance_3.setTransform(-23.7,-7.6);
	this.instance_3.alpha = 0.59;

	this.addChild(this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-193.3,-90.8,296.4,156.5);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ14();
	this.instance.setTransform(-0.2,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({y:-1.7},0).wait(1));

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#66CC00").s().p("AkIEJQhuhuAAibQAAiaBuhuQBuhuCaAAQCbAABtBuQBvBuAACaQAACbhvBuQhtBuibAAQiaAAhuhug");
	this.shape.setTransform(0,1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#66FF33").s().p("AkIEJQhuhuAAibQAAiaBuhuQBuhtCaAAQCbAABtBtQBvBuAACaQAACbhvBuQhtBuibAAQiaAAhuhug");
	this.shape_1.setTransform(0,-1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).wait(1));

	// Слой 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#669900").s().p("AkIEJQhuhuAAibQAAiaBuhuQBuhuCaABQCbgBBtBuQBvBuAACaQAACbhvBuQhtBtibAAQiaAAhuhtg");
	this.shape_2.setTransform(0,2.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37.5,-36.5,75,76.8);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 4
	this.instance = new lib.Символ12();
	this.instance.setTransform(80.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({x:-53.8},0).wait(1));

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("AF+AxQgJgIAAgPIAAgqIANAAIAAAqQAAAFACADQABAEACACQAFAGAIgBQAJABAFgGQACgCABgEQABgDAAgFIAAgqIAOAAIAAAqQAAAHgCAHQgCAFgEAEQgJAJgPAAQgOAAgIgJgAEwA2QgHgDgFgFQgGgGgDgHQgDgHAAgIQAAgIADgGQADgGAGgFQAFgGAHgDQAHgDAIAAIABAAQAIAAAHADQAGADAGAGQALAJAAAQQAAAIgDAHQgCAHgGAGQgGAFgHADQgGAEgJAAQgIAAgHgEgAE2gEQgFACgEACQgDAEgCAEQgCAFAAAFQAAAMAHAHQAEAFAFABQAEACAGAAQAFAAAEgCQAFgBAEgFQADgEACgEQABgFABgGQgBgFgBgFQgCgEgDgEQgIgGgKgBQgGAAgEADgABLAuQgGgFgCgIQgDgHAAgIQAAgPALgKQALgLAQAAQAHAAAHADQAHAFAGAGIAAgMIANAAIAABHIgNAAIAAgLQgGAGgHAEQgHAEgHAAQgRAAgKgMgABVAAQgDADgCAEQgCAFAAAGQAAAGACAFQABAFAEADQAHAIAMAAIAAAAQAEAAAFgCQAEgBAEgFQAIgHAAgMQAAgGgCgFQgCgEgEgDQgHgHgLAAQgLAAgHAHgAgVA6QgRgBgLgLQgKgKAAgSQAAgIACgHQADgEAGgHQALgLAQAAQAJABAGACQAGADAEAFQAFAGADAFQACAHAAAJIAAADIg8AAQAAAFACAFQACAEADADQAHAHALgBQAOAAAHgMIAMAHQgHAIgHAFQgIAEgLABgAAAAMQAAgGgBgDIgFgEQgGgGgJAAQgJAAgHAGIgFAEIgEAJIAuAAIAAAAgAlJA6QgRgBgLgLQgLgKAAgSQAAgIADgHQADgEAGgHQAKgLARAAQAIABAHACQAHADAFAFQAFAGADAFQACAHAAAJIAAADIg+AAQAAAFACAFQACAEAEADQAGAHALgBQAOAAAJgMIAMAHQgGAIgJAFQgJAEgLABgAkyAMQAAgGgDgDIgFgEQgHgGgIAAQgJAAgHAGIgGAEIgDAJIAwAAIAAAAgAIgA3IAAg7IgNAAIAAgMIANAAIAAgZIANAAIAAAZIAPAAIAAAMIgPAAIAAA7gAH6A3IAAguQAAgJgEgCQgCgCgDgCIgHgBQgFAAgFAEQgGADgEAFIAAAyIgOAAIAAhHIAOAAIAAAJQAFgGAGgDQAGgDAGAAQAMABAHAHQADAEACAFQACADgBAFIAAAxgAD8A3IAAguQAAgJgDgCQgDgFgGAAQgFAAgFAEQgEADgFAFIAAAyIgNAAIAAguQAAgJgDgCQgBgCgCgCIgHgBQgEAAgFAEQgFADgFAFIAAAyIgMAAIAAhIIAMAAIAAAJQALgLAMAAQAHAAAFADQAFAEADAGQAFgGAGgEQAGgDAHAAQAFAAAFACQAEACADAEQAGAHAAAKIAAAwIgBABgAhYA3IAAguQAAgJgEgCQgBgCgDgCIgHgBQgFAAgGAEQgFADgFAFIAAAyIgOAAIAAhvIAOAAIAAAxQAFgGAHgDQAFgDAHAAQAMABAGAHQADAEADAFQABADAAAFIAAAxgAixA3IAAg7IgOAAIAAgMIAOAAIAAgZIAMAAIAAAZIAPAAIAAAMIgPAAIAAA7gAkVA3IAAhHIANAAIAAALQALgOALAAIAHABIgCAPIgHgBQgLAAgJAKIAAAxgAmSA3IAAg7IgOAAIAAgMIAOAAIAAgZIAMAAIAAAZIAPAAIAAAMIgPAAIAAA7gAm6A3IAAguQABgJgEgCQgCgCgDgCIgGgBQgGAAgGAEQgEADgGAFIAAAyIgNAAIAAhHIANAAIAAAJQAGgGAGgDQAGgDAHAAQALABAHAHQADAEACAFQACADAAAFIAAAxgAo7A3IAAhtIA+AAIAAANIgwAAIAAAjIAuAAIAAAMIguAAIAAAkIAyAAIAAANg");
	this.shape.setTransform(15.7,-0.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},1).wait(1));

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("rgba(204,204,204,0.608)").ss(1,1,1).p("AvSjHIelAAIAAGPI+lAAg");
	this.shape_1.setTransform(28.7,1.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AvSDIIAAmPIelAAIAAGPg");
	this.shape_2.setTransform(28.7,1.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-70.3,-19.9,197.9,42);


// stage content:



(lib.vvod_72890 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
		
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 3
	this.instance = new lib.Символ2();
	this.instance.setTransform(659.5,43.3,1.04,1.04);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 4
	this.instance_1 = new lib.Символ5();
	this.instance_1.setTransform(89.5,43.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 2
	this.instance_2 = new lib.Символ1();
	this.instance_2.setTransform(531,44.5,0.851,0.875);
	new cjs.ButtonHelper(this.instance_2, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Слой 1
	this.instance_3 = new lib.Символ7();
	this.instance_3.setTransform(312.4,64);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// Слой 7
	this.instance_4 = new lib.Символ21();
	this.instance_4.setTransform(356.6,46.7,1.039,1);
	new cjs.ButtonHelper(this.instance_4, 0, 1, 2, false, new lib.Символ21(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// Слой 5
	this.instance_5 = new lib.wood();
	this.instance_5.setTransform(0,-14.1,0.918,0.918);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(260.1,-17.9,838.3,259.7);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;