(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 24,
	color: "#663300",
	manifest: [
		{src:"images/CASE.png", id:"CASE"},
		{src:"images/wood.jpg", id:"wood"}
	]
};



// symbols:



(lib.CASE = function() {
	this.initialize(img.CASE);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,211);


(lib.wood = function() {
	this.initialize(img.wood);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,800,200);


(lib.Символ15 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AixBTQgPgDgKgKQgKgJgFgRQgDgJgCgLIgBgYQAAgNABgLQACgLADgJQAGgRALgJQALgJAQgDQAPgDATAAQASAAAPADQAQADALAFIgJAbIgjgJIgQgBQgKAAgJABQgKACgGAFQgGAGgFAMQgDALAAAUQAAARACAMQADAMAGAGQAGAHAKACQAJACAPAAIAQgBIAOgEIAAgqIgmAAIACgaIBFAAIAABXIgNAFIgkAIIgTABQgTAAgQgDgACHBTIAAiJIgzAAIADgcICJAAIgCAcIg0AAIAACJgAgrBTIAAilIB7AAIgCAcIhWAAIAAAnIBDAAIAAAaIhDAAIAAAsIBYAAIgCAcg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-22.4,-8.6,44.9,17.3);


(lib.Символ13 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(1,1,1).p("AAAhuIAADd");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,-12.1,2,24.4);


(lib.Символ11 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AzzqiMAjiAAAIEFU2MgnnAAPg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-126.8,-67.5,253.7,135.1);


(lib.Символ10 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Av+N9Ig+jdIhfiyQhbioAAgdQAAgnAagxQAYgyAAgIQAAh+gviHQgbhLgGgZQgPg5AAg3QAAhRAkg/QAfg1AxgcQAbgPAYgDIgDgNQgHgogBgnQAAhBCPg4QBUgfAsgSQBNgeAugeQBshGCUg0QDRhKAABnQAAAelJCgQk9CbgSAAQgQAAgQgNQgQgNgDAAQgJAAgGAEQgGAFgMACQACARAAAqQAAAtgCAIQgIAhgfAFQgEALgNALQgLALggAWQg/AxAABQQAAAiAPAtIAiBaQAvCIAACdQAAApgaAsQgaArAAAXQBLCcBLCjQCVFGAAAoQAAAVgKAPQgOAXgcAAQg0AAgziUgApyMzQhijxglhDQgZgrgfhUIgyiIQgphsg/gsQgagRgHgOQgMgWAAgvQAAgJAIg6QAHg5AAgJQAAgKgHhOQgIhPAAgJQAAgYARgnQAQgnATgWQAWgYAOAPQAKAMAEAhIABABQA8AwApBgQASAnAgA8IA9BwQAgA6BKDKQA8CmAPAAQAKAACWgxQCug5BSgqQBGgkBrghQBEgUBygcQAzgMBXhDQBYhBArgLQBFgQB6hAIAegQQAIgTAYABIAtgbQAhAAANAbQAGAOABAPIgBALQAdATAgAcQBRBFA1BWQA8BjAABUQAAAXgMARQgNAUgbAAQggAAgshgQgphrgKgVQgXgyhjhGIgWgQIgFACQhEAoiRAoQg/ARhjBBQhnBDhLAYImOCaQlDB7hUAAQgvAAhMioQhAiOgbh0QgRhNhiiuIgQgeIAFBCIgIBKIgHBBQAAADAUAGQAbAIAUAQQBHA3ATCeQAGA4AnBFQAWAoAvBMQA2BfBXC3QBXC4AAATQAAASgJAQQgOAWgcAAQhDAAhfjPgAStBNQg0iJgQglQgjhrgWgyQgmhXhFgeQjAhWhijOQgOgfgIgsIgMhMQgFgWgtg/Qgsg8AAgDQAAhLBBAiQAyAaAeAoQAeAcAQAzQAFARANA9QAkC5DRBzQB7BDAhBJQAKAVAMAvQAMAxAOAfQAVAxAmBjQA0CFAAAXQAAAmgDANQgLAignAAQgTAAgvh4g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-131.6,-104.1,263.3,208.3);


(lib.Символ9 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(0,255,0,0)","#FFFFFF","rgba(0,255,0,0)"],[0,0.537,1],-31.1,-18.2,31.1,18.1).s().p("AqUGjIK6ywIJvFrIq6Swg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-66.1,-78.2,132.3,156.5);


(lib.Символ6 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.CASE();
	this.instance.setTransform(-146.1,-31.4,0.815,0.815,-23);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-146.1,-126.9,292.4,253.9);


(lib.Символ4 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#66CC33").s().p("AFfEvIAZg2IgXgyIAUAAIANAdIANgdIATAAIgwBogAEOECQgXAAgQgQQgPgPAAgYIAAgEIBqAAIAAAFIAAAEIhXAAQABAHACAHQADAFAFAFQAJAJAPAAQAUAAANgQIAQAIQgJAMgMAHQgMAFgQABgAAJD+QgJgEgHgIQgIgIgEgKQgEgKAAgLIAAgEIAUAAIAAAFQAAAPAIALQAFAGAGADQAGACAIAAQAIAAAGgDQAHgCAFgGQAFgFACgIQADgGAAgIIAAgEIATAAIAAAEQAAALgEAKQgEAKgIAIQgIAIgKAEQgKAEgLAAQgMAAgJgEgAk/ECQgXAAgPgQQgPgPAAgYIAAgEIBqAAIAAAFIAAAEIhXAAQAAAHADAHQADAFAEAFQAKAJAPAAQAUAAANgQIAQAIQgJAMgMAHQgMAFgQABgAHoD9QgFgDAAgGQAAgFAEgEQAEgEAGAAIAAAAQAFAAAEAEQAEAEAAAFQAAAGgEADQgEAFgFAAQgFAAgEgFgACwD+IAAg3IASAAIAAA3gABqD+IAAg3IATAAIAAA3gAg+D+IAAg3IATAAIAAA3gAh8D+IAAg3IATAAIAAA3gAi7D+IAAg3IATAAIAAA3gAmcD+IAAg3IASAAIAAA3gAniD+IAAg3IATAAIAAA3gAoaD+IAAg3IATAAIAAA3gAHoDXIAAgCQAAgHACgHIAWAAIgDAFQgCADAAAGIAAACgAHPAjQgHgFgEgHQgEgHgBgIIATAAQABAFACAEQADADAEADQAIAGANAAQAPAAAKgKQAKgIAAgPIAAgQQgHAJgKAEQgKAFgKABQgWAAgPgQQgHgIgDgJQgEgJAAgMIAAAAIAUAAIAAACQAAAPAJAKQAJAKAQAAIAAAAQAOgBAKgJQAKgLAAgPIAAgBIASAAIAAAyQAAAVgOAOQgPAPgZAAQgTAAgOgKgArWAtIAZg0IgWgwIAUAAIANAbIAMgbIATAAIgvBkgAJyAAQgXAAgPgOQgPgOAAgZIAAgCIBqAAIAAADIAAAFIhXAAQAAAHADAFQADAGAEAFQAKAJAPAAQAUAAANgRIAQAJQgJAMgMAHQgMAEgQAAgAEpgCQgKgEgIgIQgIgJgEgJQgEgKAAgLIAAgCIAUAAIAAACQAAAQAKALQAFAGAGADQAGACAIAAQAIAAAGgDQAHgCAFgGQAFgGACgGQADgHAAgIIAAgCIATAAIAAACQAAALgEAKQgEAJgIAJQgIAIgKAEQgKACgLAAQgMAAgJgCgAiZgOQgIgIgDgKQgEgJAAgMIAAgCIAUAAIAAACQAAAIACAHQADAHAEAFQAKAKAQAAIAAABQAHAAAHgDQAGgCAFgGQAKgLAAgQIAAgCIATAAIAAA2IgTAAIAAgQQgHAJgKAEQgKAEgKAAQgYAAgOgOgAnmgKQgMgLAAgVIAAgNIATAAIAAANQAAAGABAFQACAFAEADQAHAIALAAQALAAAHgIQADgDACgFQACgEAAgHIAAgNIATAAIAAAOQAAAJgDAIQgDAIgGAGQgMAKgUAAQgUAAgMgKgApTgCQgJgEgIgIQgJgJgEgJQgEgKAAgLIAAgCIAUAAIAAACQAAAQAKALQAFAGAHADQAGACAIAAQAHAAAHgDQAGgCAFgGQAFgGADgGQACgHAAgIIAAgCIATAAIAAACQAAALgEAKQgEAJgIAJQgIAIgKAEQgJACgMAAQgLAAgKgCgALEgBIAAg2IATAAIAAA2gADWgBIAAg2IATAAIAAA2gABdgBIAAg2IATAAIAAA2gAAngBIAAg2IASAAIAAA2gAgdgBIAAg2IATAAIAAA2gAjlgBIgVg2IASAAIAJAXIAJgXIATAAIgXA2gAkogBIgWg2IATAAIAKAXIAJgXIARAAIgWA2gAFIj1QgKgFgIgHQgPgQAAgXIAAgGIATAAIAAAFQAAAIADAHQACAGAFAGQAKAKAQAAQAIAAAHgBQAIgCAHgFIAAATIgPAFIgPACIAAAAQgMAAgKgDgADGj9QgMgMAAgUIAAgRIATAAIAAAQQAAAHABAEQACAGAEADQAHAHALAAQALAAAHgHQADgDACgGQACgEAAgGIAAgRIATAAIAAARQAAAKgDAIQgDAHgGAHQgMAMgUgBQgUABgMgMgAkvj1QgJgFgIgIQgJgIgEgKQgEgKAAgKIABgGIAUAAIgBAGQAAAQAKALQAFAFAHADQAGADAIgBQAHAAAHgCQAGgDAFgFQAFgGADgHQACgHAAgHIAAgGIATAAIAAAGQAAAKgEAKQgEAKgIAIQgIAIgKAFQgJADgMAAQgLAAgKgDgAHVj1IAAg5IASAAIAAA5gAGPj1IAAg5IATAAIAAA5gACMj1IAAg5IATAAIAAA5gABOj1IAAg5IATAAIAAA5gAAPj1IAAg5IATAAIAAA5gAhtj1IgWg5IASAAIAKAaIALgaIASAAIgYA5gAiwj1IgXg5IATAAIALAbIAKgbIARAAIgXA5gAl9j1IAAg5IAUAAIAAA5gAnij1IAAg5IAUAAIAAA5g");
	this.shape.setTransform(0,5.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#66FF00").s().p("AHqEvIACgFQAFgJAIgFQASgKAFgJQAGgJgBgKQAAgGgCgFQgCgGgFgEQgDgEgHgDQgFgCgIAAQgGAAgGACQgGACgEAEQgJAIgCAOIgTAAQABgWAQgNQAPgNAVAAQALAAAJADQAKAEAHAHQAPAOAAAUQgBAPgHANQgFAGgHAHQgGAGgLAGIgFAEgAGPEvIAWgwIATAAIgWAwgAFhEvIgWgwIAUAAIAWAwgADYEvQABgKADgIQAEgKAIgIQAPgQAXAAQAMAAAJAEQAKAEAHAIQAHAIADAKQADAIABAKgAD4EUQgFAEgDAFIgEALIBDAAQgBgGgDgFQgDgFgFgEQgJgIgMAAQgNAAgJAIgACwEvIAAgJQAAgNgFgGQgDgEgEgBQgEgCgGAAQgHAAgHAFQgIAFgHAJIAAAQIgTAAIAAgwIATAAIAAANQAIgIAIgEQAJgEAJAAQAQAAAKAKQAEAFACAHQADAHAAAJIAAANgABBEvQAAgGgCgFQgDgHgFgFQgKgLgPAAQgIAAgGADQgGACgFAGQgFAFgBAHQgCAFAAAGIgVAAQABgKAEgIQADgJAJgIQAHgIAIgEQAKgFALAAIABAAQAMAAAJAFQAJAEAJAIQAOAOABAVgAg+EvIAAgJQAAgOgFgGQgDgGgKAAQgHAAgGAFQgGAFgHAJIAAAQIgTAAIAAgJQAAgNgDgGQgDgEgDgBQgEgCgFAAQgGAAgGAFQgHAFgHAJIAAAQIgTAAIAAgwIATAAIAAAMQAOgQASAAQAKAAAHAFQAHAFAEAJQAHgJAIgFQAJgFAKAAQAIAAAFADQAGACAEAFQAJAKgBASIAAAOgAl1EvQABgKAEgIQADgKAIgIQAQgQAWAAQANAAAJAEQAJAEAIAIQAGAIAEAKQADAIAAAKgAlVEUQgEAEgEAFIgDALIBCAAQgBgGgCgFQgEgFgEgEQgJgIgNAAQgNAAgJAIgAmcEvIAAgJQAAgNgGgGQgCgEgEgBQgEgCgFAAQgIAAgIAFQgHAFgHAJIAAAQIgTAAIAAhpIATAAIAABGQAHgIAJgEQAIgEAJAAQARAAAKAKQAFAFACAHQACAHAAAJIAAANgAobEvIAAggIgSAAIAAgQIASAAIAAgjIATAAIAAAjIAUAAIAAAQIgUAAIAAAggALEAuIAAghIgTAAIAAgOIATAAIAAgjIATAAIAAAjIATAAIAAAOIgTAAIAAAhgAI9AuQAAgKADgJQAEgKAIgIQAPgOAYAAQAMAAAJAEQAJACAIAIQAGAIAEAKQADAIAAALgAJcASQgEAEgEAFIgDALIBCAAQgBgGgCgFQgDgFgFgEQgJgIgMAAQgNAAgKAIgAITAuQAAgHgCgGQgDgGgEgFQgLgLgOAAQgHAAgGADQgHACgEAFQgJAKAAAPIgVAAQABgWAOgPQAHgIAKgBQAIgEAMAAQAJAAAKAEQAKAEAHAJIAAgOIATAAIAAAvgAFhAuQAAgHgCgFQgDgHgFgFQgKgLgPAAQgIAAgGADQgGACgFAGQgGAFgCAHQgCAGgBAGIgUAAQABgKAEgJQADgJAJgIQAIgIAJgCQAKgFALAAIABAAQAMAAAJAFQAJACAJAIQAPAPAAAVgADWAuIAAghIgTAAIAAgOIATAAIAAgjIATAAIAAAjIATAAIAAAOIgTAAIAAAhgABcAuIAAghIgSAAIAAgOIASAAIAAgjIATAAIAAAjIAVAAIAAAOIgVAAIAAAhgAAmAuIAAgKQABgNgGgGQgDgEgDgBQgEgCgGAAQgIAAgHAFQgGAFgGAJIAAARIgTAAIAAgvIATAAIAAALQAHgIAGgCQAJgEAJAAQARAAAJAIQAFAFACAHQACAHAAAJIAAAOgAhOAuQAAgHgCgGQgDgGgGgGQgKgLgPAAQgPAAgKALQgFAFgCAHQgCAGgBAHIgUAAQABgVAPgPQAPgOAWAAQALAAAKAEQAKAFAHAJIAAgOIATAAIAAAugAjWAuIATgvIATAAIgUAvgAj6AuIgHgSIgGASIgRAAIATgvIAKAAIATAvgAk/AuIgUgvIAUAAIAUAvgAmuAuIAAgvIATAAIAAAvgAnzAuIAAgvIAUAAIAAAvgAoaAuQAAgHgCgFQgDgHgFgFQgKgLgQAAQgHAAgGADQgHACgFAGQgFAFgDAHQgCAGAAAGIgUAAQAAgKAEgJQAEgJAJgIQAIgIAJgCQAKgFALAAIAAAAQAMAAAJAFQAKACAIAIQAPAPABAVgAqmAuIAWgvIATAAIgWAvgArTAuIgXgvIAVAAIAWAvgAHVjHIAAgGQAAgOgFgGQgDgDgEgCQgEgBgFAAQgIAAgIAFQgHAEgHAKIAAANIgTAAIAAhnIATAAIAABGQAIgIAIgEQAJgEAIAAQARAAAKALQAFAFACAHQACAHAAAIIAAALgAEnjHQAAgIADgIQAFgKAIgHQAQgQAXAAQAIAAAIACQAHABAGAEIAAASQgNgIgQAAQgPAAgLAKQgIAJgCANgAD+jHIAAgtIATAAIAAAtgAC6jHIAAgtIATAAIAAAtgACMjHIAAgGQgBgPgEgFQgEgGgIAAQgIAAgGAFQgHAEgFAJIAAAOIgTAAIAAgHQAAgNgFgGQgCgDgDgCQgDgBgFAAQgHAAgHAFQgGAEgGAJIAAAOIgTAAIAAguIATAAIAAANQANgQARAAQALAAAHAFQAHAEADAJQAIgJAIgFQAJgEAKAAQAHAAAGACQAGADAFAFQAHAKABASIAAALgAhcjHIASgtIATAAIgTAtgAiDjHIgFgOIgHAOIgQAAIASgtIAKAAIASAtgAjIjHIgSgtIAUAAIASAtgAj2jHIgDgJQgCgGgFgGQgKgLgPAAQgIAAgHADQgGADgFAFQgFAGgCAHIgCAIIgVAAQABgIADgHQAEgKAIgIQAJgIAJgEQAJgEAMAAIABAAQALAAAKAEQAJAEAIAIQAOAOACATgAl+jHIAAgQIhQAAIAAAQIgVAAIAAhjIAVAAIAABBIBQAAIAAhBIAVAAIAABjg");
	this.shape_1.setTransform(0,-4.5);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-74.7,-34.8,149.4,71);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ15();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.621},4).to({alpha:1},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.4,-8.6,44.9,17.3);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ13();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({alpha:0.172},0).wait(5).to({alpha:1},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.5,-11.6,1,23.4);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AFfFiIAZg2IgXgxIAUAAIANAcIANgcIATAAIgwBngAEOE1QgYAAgPgPIAAAAQgPgPAAgZIAAAAIAAgDIAAAAIBqAAIAAAEIAAAAIAAAFIhXAAQABAHACAGIAAAAQADAGAEAFIAAAAQAKAIAPABIAAAAQAUgBANgQIAAAAIAQAJQgJAMgMAHIAAAAQgMAFgQAAIAAAAgAAJEyQgJgFgHgHIAAAAQgJgJgDgJIAAAAQgFgLAAgLIAAAAIAAgDIAAAAIAVAAIgBAEIAAAAQAAAQAJAKIAAAAQAFAGAGADIAAAAQAGADAIAAIAAAAQAHgBAHgDIAAAAQAHgCAEgGIAAAAQAFgFADgHIAAAAQACgGAAgJIAAAAIAAgDIAAAAIATAAIAAADIAAAAQAAALgDALIAAAAQgFAJgHAJIAAAAQgJAHgJAFIAAAAQgKADgMAAIAAAAQgLAAgJgDgAk/E1QgXAAgQgPIAAAAQgPgPAAgZIAAAAIAAgDIAAAAIBqAAIAAAEIAAAAIAAAFIhWAAQAAAHADAGIAAAAQADAGAEAFIAAAAQAJAIAPABIAAAAQAVgBAMgQIAAAAIARAJQgKAMgLAHIAAAAQgMAFgRAAIAAAAgAHnExQgEgEAAgFIAAAAQAAgGAEgDIAAAAQAEgEAFgBIAAAAIABAAQAFABAEAEIAAAAQAEADAAAGIAAAAQAAAFgEAEIAAAAQgEAEgFAAIAAAAQgFAAgFgEgACwEyIAAg3IASAAIAAA3gABqEyIAAg3IATAAIAAA3gAg+EyIAAg3IATAAIAAA3gAh8EyIAAg3IASAAIAAA3gAi7EyIAAg3IASAAIAAA3gAmcEyIAAg3IASAAIAAA3gAniEyIAAg3IATAAIAAA3gAobEyIAAg3IATAAIAAA3gAHnELIAAgDQABgHACgGIAAAAIAWAAIgDAEIAAAAQgDADAAAGIAAAAIAAADgAHqD7IACgFIAAAAQAFgJAIgEIAAAAQASgLAFgJIAAAAQAGgJgBgJIAAAAQAAgHgCgFIAAAAQgCgGgFgEIAAAAQgDgEgHgCIAAAAQgFgDgIAAIAAAAQgGAAgGADIAAAAQgGACgEADIAAAAQgJAIgCAPIAAAAIgTAAQABgXAQgNIAAAAQAPgNAVAAIAAAAQALAAAJAEIAAAAQAKADAHAHIAAAAQAPAOAAAVIAAAAQgBAPgHANIAAAAQgFAFgHAHIAAAAQgGAGgLAHIAAAAIgFADIAAAAgAGPD7IAWgvIATAAIgWAvgAFhD7IgWgvIAUAAIAWAvgADYD7QABgJADgJIAAAAQAEgJAIgIIAAAAQAPgQAXgBIAAAAQAMAAAJAFIAAAAQAKAEAHAHIAAAAQAHAIADAKIAAAAQAEAIAAAKIAAAAgAD4DgQgFAEgDAFIAAAAIgEALIAAAAIBDAAQgBgGgDgFIAAAAQgDgFgFgEIAAAAQgJgIgMAAIAAAAQgNAAgJAIgACwD7IAAgIQAAgOgFgGIAAAAQgDgDgEgCIAAAAQgEgBgGgBIAAAAQgHAAgHAGIAAAAQgIAEgHAJIAAAAIAAAQIgTAAIAAgvIATAAIAAAMQAIgIAIgEIAAAAQAJgEAJAAIAAAAQAQAAAKAKIAAAAQAEAGACAHIAAAAQADAGAAAJIAAAAIAAANgABBD7QAAgGgCgFIAAAAQgDgGgFgGIAAAAQgKgLgPAAIAAAAQgIAAgGADIAAAAQgGACgFAGIAAAAQgFAFgBAIIAAAAQgCAEAAAGIAAAAIgVAAQABgJAEgIIAAAAQADgKAJgIIAAAAQAHgIAJgEIAAAAQAJgEALgBIAAAAIABAAQAMABAJAEIAAAAQAJAEAJAIIAAAAQAOAPABAUIAAAAgAg+D7IAAgIQAAgPgFgFIAAAAQgDgHgJAAIAAAAQgIAAgGAGIAAAAQgGAEgHAJIAAAAIAAAQIgSAAIAAgJQAAgNgEgGIAAAAQgDgDgDgCIAAAAQgEgBgEgBIAAAAQgHAAgGAGIAAAAQgHAEgHAJIAAAAIAAAQIgSAAIAAgwIASAAIAAANQAOgQASgBIAAAAQAKAAAHAGIAAAAQAHAEAEAJIAAAAQAHgJAIgFIAAAAQAJgEAKgBIAAAAQAIABAFACIAAAAQAGACAEAFIAAAAQAJALAAARIAAAAIAAAOgAl1D7QABgJAEgJIAAAAQADgJAIgIIAAAAQAQgQAWgBIAAAAQANAAAJAFIAAAAQAJAEAIAHIAAAAQAGAIAEAKIAAAAQADAIAAAKIAAAAgAlVDgQgEAEgEAFIAAAAIgDALIAAAAIBCAAQgBgGgCgFIAAAAQgEgFgEgEIAAAAQgJgIgNAAIAAAAQgMAAgKAIgAmcD7IAAgIQAAgOgGgGIAAAAQgCgDgEgCIAAAAQgEgBgFgBIAAAAQgIAAgIAGIAAAAQgHAEgHAJIAAAAIAAAQIgTAAIAAhpIATAAIAABGQAHgIAJgEIAAAAQAIgEAJAAIAAAAQARAAAKAKIAAAAQAFAGACAHIAAAAQACAGAAAJIAAAAIAAANgAobD7IAAggIgSAAIAAgPIASAAIAAgjIATAAIAAAjIAUAAIAAAPIgUAAIAAAggAHPBWQgHgFgEgHIAAAAQgEgHgBgIIAAAAIATAAQAAAFADAEIAAAAQADADAEADIAAAAQAIAHAMAAIAAAAQAQAAAKgKIAAAAQAKgJgBgQIAAAAIAAgRQgGAJgKAFIAAAAQgKAFgKAAIAAAAQgWAAgPgPIAAAAQgHgIgDgJIAAAAQgFgKAAgKIAAAAIAAAAIAVAAIAAACIAAAAQAAAOAJAJIAAAAQAJALAPAAIAAAAIAAgBQAOAAALgKIAAAAQAKgKgBgNIAAAAIAAgCIAAAAIATAAIAAAxQAAAXgOAOIAAAAQgPAPgZAAIAAAAQgUAAgNgLgArWBhIAZg2IgWgvIAUAAIAMAZIANgZIATAAIgwBlgAJyA0QgXAAgQgQIAAAAQgOgPAAgXIAAAAIAAgCIAAAAIBpAAIAAAEIAAAAIAAACIhWAAQAAAHACAGIAAAAQADAGAFAFIAAAAQAKAJAPAAIAAAAQATAAANgRIAAAAIAQAJQgJAMgLAGIAAAAQgMAGgQABIAAAAgAEpAvQgKgDgIgIIAAAAQgJgJgDgJIAAAAQgFgLAAgIIAAAAIAAgDIAAAAIAUAAIAAADIAAAAQAAANALAMIAAAAQAFAFAGADIAAAAQAGACAIABIAAAAQAHAAAHgDIAAAAQAHgDAEgFIAAAAQAFgGADgHIAAAAQACgHAAgFIAAAAIAAgDIAAAAIATAAIAAADIAAAAQAAAIgDALIAAAAQgFAJgHAJIAAAAQgJAIgJADIAAAAQgKAFgMAAIAAAAQgLAAgJgFgAiZAkQgIgIgDgKIAAAAQgFgKAAgJIAAAAIAAgDIAAAAIAUAAIAAACIAAAAQAAAHADAGIAAAAQADAHAEAGIAAAAQAKAKAQAAIAAAAIAAABQAHAAAHgDIAAAAQAFgDAGgFIAAAAQAKgMAAgOIAAAAIAAgCIAAAAIATAAIAAA0IgTAAIAAgQQgHAJgKAFIAAAAQgKAFgKABIAAAAQgYgBgOgPgAnmAnQgNgLAAgUIAAAAIAAgMIAUAAIAAAMQAAAFABAFIAAAAQACAFADAEIAAAAQAIAHAKABIAAAAQAMgBAGgHIAAAAQAEgEACgFIAAAAQACgEgBgGIAAAAIAAgMIATAAIAAANQAAAJgCAIIAAAAQgEAIgFAFIAAAAQgMAMgVABIAAAAQgTgBgMgMgApTAvQgJgDgIgIIAAAAQgJgJgEgJIAAAAQgEgLAAgIIAAAAIAAgDIAAAAIAUAAIAAADIAAAAQAAANAKAMIAAAAQAFAFAHADIAAAAQAGACAHABIAAAAQAIAAAHgDIAAAAQAGgDAFgFIAAAAQAFgGADgHIAAAAQACgHAAgFIAAAAIAAgDIAAAAIATAAIAAADIAAAAQAAAIgEALIAAAAQgEAJgIAJIAAAAQgIAIgKADIAAAAQgKAFgLAAIAAAAQgLAAgKgFgALEAwIAAg0IATAAIAAA0gADWAwIAAg0IATAAIAAA0gABcAwIAAg0IATAAIAAA0gAAmAwIAAg0IASAAIAAA0gAgdAwIAAg0IATAAIAAA0gAjlAwIgVg0IASAAIAJAWIAJgWIASAAIgWA0gAkoAwIgXg0IAUAAIAKAWIAJgWIARAAIgXA0gALEgEIAAggIgTAAIAAgQIATAAIAAgkIATAAIAAAkIAUAAIAAAQIgUAAIAAAggAI9gEQAAgKADgJIAAAAQAEgJAIgJIAAAAQAPgPAYAAIAAAAQAMAAAJAEIAAAAQAJADAIAIIAAAAQAGAIAEAKIAAAAQADAIAAALIAAAAgAJcggQgEAEgEAFIAAAAIgDAMIAAAAIBCAAQgBgHgCgFIAAAAQgDgFgFgEIAAAAQgJgIgMAAIAAAAQgNAAgKAIgAITgEQAAgHgCgFIAAAAQgDgHgEgFIAAAAQgLgLgOABIAAAAQgHAAgGACIAAAAQgHADgEAFIAAAAQgJAJAAAPIAAAAIgVAAQAAgWAPgPIAAAAQAHgHAKgEIAAAAQAIgEAMAAIAAAAQAJAAAKAFIAAAAQAKAFAHAJIAAAAIAAgPIATAAIAAAwgAFhgEQAAgHgCgFIAAAAQgDgGgFgGIAAAAQgKgLgPAAIAAAAQgIAAgGADIAAAAQgGADgFAFIAAAAQgGAGgCAGIAAAAQgCAGgBAGIAAAAIgUAAQABgKAEgJIAAAAQADgJAJgIIAAAAQAIgIAKgEIAAAAQAJgFALABIAAAAIABAAQAMgBAJAFIAAAAQAJAEAJAIIAAAAQAOAPABAVIAAAAgADWgEIAAggIgTAAIAAgQIATAAIAAgkIATAAIAAAkIATAAIAAAQIgTAAIAAAggABcgEIAAggIgSAAIAAgQIASAAIAAgkIATAAIAAAkIAVAAIAAAQIgVAAIAAAggAAmgEIAAgKQABgNgGgGIAAAAQgDgEgDgBIAAAAQgEgCgGAAIAAAAQgIABgHAFIAAAAQgGAEgGAKIAAAAIAAAQIgTAAIAAgwIATAAIAAAMQAHgIAGgEIAAAAQAJgEAJAAIAAAAQARAAAJALIAAAAQAFAFACAGIAAAAQACAIAAAIIAAAAIAAAOgAhOgEQAAgHgCgFIAAAAQgDgHgFgFIAAAAQgLgMgPAAIAAAAQgPAAgKALIAAAAQgFAFgCAHIAAAAQgCAGgBAHIAAAAIgUAAQABgVAPgPIAAAAQAPgPAXAAIAAAAQAKAAAKAEIAAAAQAKAGAHAJIAAAAIAAgQIATAAIAAAwgAjWgEIATgwIATAAIgUAwgAj6gEIgHgSIgGASIgRAAIATgwIAKAAIATAwgAk/gEIgUgwIAUAAIAUAwgAmugEIAAgwIATAAIAAAwgAnzgEIAAgwIAUAAIAAAwgAoagEQAAgHgCgFIAAAAQgDgGgFgGIAAAAQgKgLgQAAIAAAAQgHAAgGADIAAAAQgHADgFAFIAAAAQgFAGgDAGIAAAAQgBAGgBAGIAAAAIgUAAQAAgKAEgJIAAAAQAEgJAJgIIAAAAQAIgIAJgEIAAAAQAKgFALABIAAAAIAAAAQAMgBAJAFIAAAAQAKAEAIAIIAAAAQAPAPABAVIAAAAgAqmgEIAWgwIATAAIgWAwgArTgEIgXgwIAVAAIAWAwgAFHjCQgJgEgIgHIAAAAQgPgQAAgYIAAAAIAAgFIAAAAIAUAAIgBAFIAAAAQAAAIACAGIAAAAQADAHAFAGIAAAAQAJAKARAAIAAAAQAIAAAHgCIAAAAQAIgCAGgEIAAAAIAAATIgOAEIAAAAQgHACgIAAIAAAAIAAABQgNAAgKgEgADGjKQgMgMAAgTIAAAAIAAgRIATAAIAAAQQgBAGACAFIAAAAQACAFAEADIAAAAQAGAIAMAAIAAAAQAKAAAIgIIAAAAQADgDACgFIAAAAQABgFAAgFIAAAAIAAgRIATAAIAAARQAAAJgDAJIAAAAQgCAHgHAGIAAAAQgMAMgTAAIAAAAQgVAAgLgMgAkvjCQgJgEgJgIIAAAAQgIgIgEgKIAAAAQgEgKAAgLIAAAAIAAgFIAAAAIAVAAIgBAGIAAAAQAAAPAKALIAAAAQAFAGAHADIAAAAQAFACAJAAIAAAAQAHAAAGgDIAAAAQAHgCAFgGIAAAAQAFgFACgIIAAAAQADgGAAgIIAAAAIAAgFIAAAAIATAAIAAAFIAAAAQAAALgEAKIAAAAQgEAKgIAIIAAAAQgIAIgKAEIAAAAQgJAEgMAAIAAAAQgMAAgJgEgAHVjCIAAg4IASAAIAAA4gAGPjCIAAg4IATAAIAAA4gACMjCIAAg4IATAAIAAA4gABOjCIAAg4IATAAIAAA4gAAPjCIAAg4IATAAIAAA4gAhtjCIgWg4IASAAIAKAaIALgaIASAAIgYA4gAixjCIgWg4IATAAIALAaIAKgaIARAAIgYA4gAl+jCIAAg4IAVAAIAAA4gAnjjCIAAg4IAVAAIAAA4gAHVj6IAAgHQAAgNgFgHIAAAAQgDgDgEgBIAAAAQgEgCgFAAIAAAAQgIAAgIAFIAAAAQgHAFgHAJIAAAAIAAAOIgTAAIAAhnIATAAIAABFQAIgHAIgEIAAAAQAJgEAIAAIAAAAQARgBAKALIAAAAQAFAFACAHIAAAAQACAHAAAJIAAAAIAAALgAEnj6QAAgJADgIIAAAAQAFgKAIgHIAAAAQAQgQAXAAIAAAAQAIAAAIACIAAAAQAHACAGADIAAAAIAAASQgNgIgPAAIAAAAQgQAAgLALIAAAAQgJAIAAAOIAAAAgAD+j6IAAguIATAAIAAAugAC6j6IAAguIATAAIAAAugACMj6IAAgHQgBgOgEgGIAAAAQgEgGgIAAIAAAAQgIAAgGAFIAAAAQgHAFgFAIIAAAAIAAAPIgTAAIAAgIQAAgMgFgHIAAAAQgCgDgDgBIAAAAQgDgCgFAAIAAAAQgHAAgHAFIAAAAQgGAFgGAIIAAAAIAAAPIgTAAIAAguIATAAIAAAMQANgQARAAIAAAAQALAAAHAFIAAAAQAHAEADAKIAAAAQAIgKAIgEIAAAAQAJgFAKAAIAAAAQAIAAAFADIAAAAQAGACAFAFIAAAAQAHAKABASIAAAAIAAAMgAhcj6IASguIATAAIgTAugAiDj6IgFgPIgGAPIgRAAIASguIAKAAIASAugAjHj6IgTguIAUAAIASAugAj2j6IgDgKIAAAAQgCgGgFgFIAAAAQgKgMgPAAIAAAAQgIABgGADIAAAAQgHACgFAGIAAAAQgFAFgCAHIAAAAIgCAJIAAAAIgVAAQABgJADgHIAAAAQAEgJAIgJIAAAAQAJgHAJgEIAAAAQAJgFAMAAIAAAAIABAAQALAAAKAFIAAAAQAJAEAIAHIAAAAQAOAPACATIAAAAgAl+j6IAAgRIhQAAIAAARIgVAAIAAhkIAVAAIAABBIBQAAIAAhBIAVAAIAABkg");

	// Слой 2
	this.instance = new lib.Символ9();
	this.instance.setTransform(-127.2,-12.9);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:150.8,y:11.8},39).wait(32));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.7,-35.5,13.7,71);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ6();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:1.3},12,cjs.Ease.get(-1)).to({rotation:3.5},17,cjs.Ease.get(1)).to({rotation:1.8},17,cjs.Ease.get(-1)).to({rotation:0},19,cjs.Ease.get(1)).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ10();
	this.instance_1.setTransform(10.1,18.9);
	this.instance_1.alpha = 0.391;
	this.instance_1.filters = [new cjs.BlurFilter(12, 12, 1)];
	this.instance_1.cache(-134,-106,267,212);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(66));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-146.1,-126.9,296.6,259.7);


(lib.Символ5 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ8();
	this.instance.setTransform(0,0.4);

	// Слой 1
	this.instance_1 = new lib.Символ4();
	this.instance_1.setTransform(0,-0.3);

	this.instance_2 = new lib.Символ4();
	this.instance_2.setTransform(0,1.6);
	this.instance_2.filters = [new cjs.ColorFilter(0.48, 0.48, 0.48, 1, 0, 0, 0, 0)];
	this.instance_2.cache(-77,-37,153,75);

	// Слой 3
	this.instance_3 = new lib.Символ11();
	this.instance_3.setTransform(-23.7,-7.6);
	this.instance_3.alpha = 0.59;

	this.addChild(this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-193.3,-90.8,296.4,156.5);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ14();
	this.instance.setTransform(-0.2,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({y:-1.7},0).wait(1));

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#66CC00").s().p("AkIEJQhuhuAAibQAAiaBuhuQBuhuCaAAQCbAABtBuQBvBuAACaQAACbhvBuQhtBuibAAQiaAAhuhug");
	this.shape.setTransform(0,1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#66FF33").s().p("AkIEJQhuhuAAibQAAiaBuhuQBuhtCaAAQCbAABtBtQBvBuAACaQAACbhvBuQhtBuibAAQiaAAhuhug");
	this.shape_1.setTransform(0,-1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).wait(1));

	// Слой 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#669900").s().p("AkIEJQhuhuAAibQAAiaBuhuQBuhuCaABQCbgBBtBuQBvBuAACaQAACbhvBuQhtBtibAAQiaAAhuhtg");
	this.shape_2.setTransform(0,2.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37.5,-36.5,75,76.8);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 4
	this.instance = new lib.Символ12();
	this.instance.setTransform(80.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({x:-53.8},0).wait(1));

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("AF+AxQgJgIAAgPIAAgqIANAAIAAAqQAAAFACADQABAEACACQAFAGAIgBQAJABAFgGQACgCABgEQABgDAAgFIAAgqIAOAAIAAAqQAAAHgCAHQgCAFgEAEQgJAJgPAAQgOAAgIgJgAEwA2QgHgDgFgFQgGgGgDgHQgDgHAAgIQAAgIADgGQADgGAGgFQAFgGAHgDQAHgDAIAAIABAAQAIAAAHADQAGADAGAGQALAJAAAQQAAAIgDAHQgCAHgGAGQgGAFgHADQgGAEgJAAQgIAAgHgEgAE2gEQgFACgEACQgDAEgCAEQgCAFAAAFQAAAMAHAHQAEAFAFABQAEACAGAAQAFAAAEgCQAFgBAEgFQADgEACgEQABgFABgGQgBgFgBgFQgCgEgDgEQgIgGgKgBQgGAAgEADgABLAuQgGgFgCgIQgDgHAAgIQAAgPALgKQALgLAQAAQAHAAAHADQAHAFAGAGIAAgMIANAAIAABHIgNAAIAAgLQgGAGgHAEQgHAEgHAAQgRAAgKgMgABVAAQgDADgCAEQgCAFAAAGQAAAGACAFQABAFAEADQAHAIAMAAIAAAAQAEAAAFgCQAEgBAEgFQAIgHAAgMQAAgGgCgFQgCgEgEgDQgHgHgLAAQgLAAgHAHgAgVA6QgRgBgLgLQgKgKAAgSQAAgIACgHQADgEAGgHQALgLAQAAQAJABAGACQAGADAEAFQAFAGADAFQACAHAAAJIAAADIg8AAQAAAFACAFQACAEADADQAHAHALgBQAOAAAHgMIAMAHQgHAIgHAFQgIAEgLABgAAAAMQAAgGgBgDIgFgEQgGgGgJAAQgJAAgHAGIgFAEIgEAJIAuAAIAAAAgAlJA6QgRgBgLgLQgLgKAAgSQAAgIADgHQADgEAGgHQAKgLARAAQAIABAHACQAHADAFAFQAFAGADAFQACAHAAAJIAAADIg+AAQAAAFACAFQACAEAEADQAGAHALgBQAOAAAJgMIAMAHQgGAIgJAFQgJAEgLABgAkyAMQAAgGgDgDIgFgEQgHgGgIAAQgJAAgHAGIgGAEIgDAJIAwAAIAAAAgAIgA3IAAg7IgNAAIAAgMIANAAIAAgZIANAAIAAAZIAPAAIAAAMIgPAAIAAA7gAH6A3IAAguQAAgJgEgCQgCgCgDgCIgHgBQgFAAgFAEQgGADgEAFIAAAyIgOAAIAAhHIAOAAIAAAJQAFgGAGgDQAGgDAGAAQAMABAHAHQADAEACAFQACADgBAFIAAAxgAD8A3IAAguQAAgJgDgCQgDgFgGAAQgFAAgFAEQgEADgFAFIAAAyIgNAAIAAguQAAgJgDgCQgBgCgCgCIgHgBQgEAAgFAEQgFADgFAFIAAAyIgMAAIAAhIIAMAAIAAAJQALgLAMAAQAHAAAFADQAFAEADAGQAFgGAGgEQAGgDAHAAQAFAAAFACQAEACADAEQAGAHAAAKIAAAwIgBABgAhYA3IAAguQAAgJgEgCQgBgCgDgCIgHgBQgFAAgGAEQgFADgFAFIAAAyIgOAAIAAhvIAOAAIAAAxQAFgGAHgDQAFgDAHAAQAMABAGAHQADAEADAFQABADAAAFIAAAxgAixA3IAAg7IgOAAIAAgMIAOAAIAAgZIAMAAIAAAZIAPAAIAAAMIgPAAIAAA7gAkVA3IAAhHIANAAIAAALQALgOALAAIAHABIgCAPIgHgBQgLAAgJAKIAAAxgAmSA3IAAg7IgOAAIAAgMIAOAAIAAgZIAMAAIAAAZIAPAAIAAAMIgPAAIAAA7gAm6A3IAAguQABgJgEgCQgCgCgDgCIgGgBQgGAAgGAEQgEADgGAFIAAAyIgNAAIAAhHIANAAIAAAJQAGgGAGgDQAGgDAHAAQALABAHAHQADAEACAFQACADAAAFIAAAxgAo7A3IAAhtIA+AAIAAANIgwAAIAAAjIAuAAIAAAMIguAAIAAAkIAyAAIAAANg");
	this.shape.setTransform(15.7,-0.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},1).wait(1));

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("rgba(204,204,204,0.608)").ss(1,1,1).p("AvSjHIelAAIAAGPI+lAAg");
	this.shape_1.setTransform(28.7,1.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AvSDIIAAmPIelAAIAAGPg");
	this.shape_2.setTransform(28.7,1.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-70.3,-19.9,197.9,42);


// stage content:



(lib.vvod_72890 = function() {
	this.initialize();

	// Слой 3
	this.instance = new lib.Символ2();
	this.instance.setTransform(659.5,43.3,1.04,1.04);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	// Слой 4
	this.instance_1 = new lib.Символ5();
	this.instance_1.setTransform(89.5,44.6);

	// Слой 2
	this.instance_2 = new lib.Символ1();
	this.instance_2.setTransform(531,44.5,0.851,0.875);
	new cjs.ButtonHelper(this.instance_2, 0, 1, 1);

	// Слой 1
	this.instance_3 = new lib.Символ7();
	this.instance_3.setTransform(312.4,64);

	// Слой 5
	this.instance_4 = new lib.wood();
	this.instance_4.setTransform(0,-14.1,0.918,0.918);

	this.addChild(this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(260.1,-17.9,838.3,259.7);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;